import { cva } from "class-variance-authority";

export const buttonStyle = cva(
  [
    "flex",
    "items-center",
    "justify-center",
    "gap-2",
    "rounded-lg",
    "leading-none",
    "ring-focus",
    "transition",
    "hover:cursor-pointer",
    "focus:outline-none",
    "focus-visible:ring-4",
    "disabled:cursor-not-allowed",
  ],
  {
    variants: {
      variant: {
        primary: [
          "bg-primary-600",
          "text-primary-50",
          "hover:bg-primary-700",
          "active:bg-primary-800",
          "disabled:bg-primary-300",
          "disabled:text-primary-800",
          "dark:bg-primary-300",
          "dark:text-primary-800",
          "dark:hover:bg-primary-200",
          "dark:active:bg-primary-100",
          "dark:disabled:bg-primary-600",
          "dark:disabled:text-primary-50",
        ],
        outline: [
          "border-2",
          "border-primary-600",
          "bg-primary-100",
          "text-primary-950",
          "hover:bg-primary-200",
          "active:bg-primary-300",
          "disabled:border-primary-400",
          "disabled:bg-primary-400",
          "disabled:text-primary-800",
          "dark:border-primary-400",
          "dark:bg-primary-950",
          "dark:text-primary-400",
          "dark:hover:bg-primary-900",
          "dark:active:bg-primary-800",
          "dark:disabled:border-primary-800",
          "dark:disabled:bg-primary-800",
          "dark:disabled:text-primary-600",
        ],
        ghost: [
          "bg-primary-50",
          "text-primary-600",
          "hover:bg-primary-50",
          "active:bg-primary-100",
          "disabled:border-primary-200",
          "disabled:bg-primary-200",
          "disabled:text-primary-400",
          "dark:bg-primary-950",
          "dark:text-primary-200",
          "dark:hover:bg-primary-950",
          "dark:active:bg-primary-900",
          "dark:disabled:border-primary-800",
          "dark:disabled:bg-primary-800",
          "dark:disabled:text-primary-200",
        ],
      },
      size: {
        sm: ["min-h-9", "px-3", "py-1.5", "text-sm"],
        md: ["min-h-10", "px-5", "py-2", "text-sm"],
        lg: ["min-h-11", "px-5", "py-2.5", "text-md"],
        xl: ["min-h-12", "px-6", "py-3", "text-md"],
      },
      btnType: {
        button: "",
        icon: ["rounded-full", "px-0"],
      },
    },
    compoundVariants: [
      { btnType: "icon", size: "sm", class: "size-9" },
      { btnType: "icon", size: "md", class: "size-10" },
      { btnType: "icon", size: "lg", class: "size-11" },
      { btnType: "icon", size: "xl", class: "size-12" },
    ],
    defaultVariants: {
      variant: "primary",
      size: "md",
      btnType: "button",
    },
  },
);
